remote_theme: vaibhavvikas/jekyll-theme-minimalistic
plugins:
  - jekyll-remote-theme

title: Unitree-Aliengo

nav_exclude: false

navigation:
  - name: Быстрый старт
    link: ./introduction.html
  - name: Технические характеристики
    link: ./specifications.html
  - name: Архитектура системы
    link: ./aliengo.html    
  - name: Гайды
    link: ./tutorials.html
  - name: Проект rl_go1 (управление робособакой через сдк)
    link: ./sdk.html    
  - name: Проект RMA (обучение RL-политик)
    link: ./rma.html    