remote_theme: vaibhavvikas/jekyll-theme-minimalistic
plugins:
  - jekyll-remote-theme

title: Unitree-Aliengo

nav_exclude: false

navigation:
  - title: Документация
    items:
      - title: Быстрый старт
        url: /introduction/
      - title: Технические характеристики
        url: /specifications/
      - title: Гайды
        url: /tutorials/