remote_theme: vaibhavvikas/jekyll-theme-minimalistic
plugins:
  - jekyll-remote-theme

title: Unitree-Aliengo

nav_exclude: false

navigation:
  - name: Aliengo
    link: ./README.md
  - name: Быстрый старт
    link: ./introduction.md
  - name: Технические характеристики
    link: ./specifications.md
  - name: Архитектура системы
    link: ./aliengo.md    
  - name: Гайды
    link: ./tutorials.md
  - name: Проект rl_go1 (управление робособакой через сдк)
    link: ./sdk.md    
  - name: Проект RMA (обучение RL-политик)
    link: ./rma.md    